export const elements = {
    settings: document.querySelector('.settings') as HTMLElement,
    closeModalSettings: document.querySelector('.close_cross_settings') as HTMLButtonElement,
    closeModalAuthorization: document.querySelector('.close_cross_authorization') as HTMLButtonElement,
    popupOverlaySettings: document.querySelector('.popup-overlay_settings') as HTMLElement,
    popupOverlayAuthorization: document.querySelector('.popup-overlay_authorization') as HTMLElement,
    messages: document.querySelector('.messages') as HTMLDivElement,
    template: document.querySelector('#messageI') as HTMLTemplateElement,
    input: document.querySelector('.inputMessage') as HTMLInputElement,
    formFooter: document.querySelector('.form_footer') as HTMLFormElement,
    mistake: document.querySelector('.mistake') as HTMLElement,
    authorization: document.querySelector('.close') as HTMLElement,
    enterCodeButton: document.querySelector('.enter_code') as HTMLButtonElement,
    popupOverlayConfirmation: document.querySelector('.popup-overlay_confirmation') as HTMLElement,
    closeModalConfirmation: document.querySelector('.close_cross_confirmation') as HTMLButtonElement,
    inputEmail: document.querySelector('.input_email') as HTMLInputElement,
    formAuthorization: document.querySelector('.authorization_form') as HTMLFormElement,
    inputCode: document.querySelector('.input_code') as HTMLInputElement,
    confirmationForm: document.querySelector('.confirmation_form') as HTMLFormElement,
    settingsForm: document.querySelector('.settings_form') as HTMLFormElement,
    inputName: document.querySelector('.input_name') as HTMLInputElement,
};
